### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by Haley-HuiM** [MartinYuanNJU/SEMScene#1]
Hi,

Thanks for sharing the code and great work!

I tried to reproduce the code, but the following error occurred that the files could not be found: 
FileNotFoundError: [Errno 2] No such file or directory: '../data_flickr30k/data/flickr30k_train_lowered_images_data_adj.joblib'
FileNotFoundError: [Errno 2] No such file or directory: '../data_flickr30k/data/flickr30k_train_lowered_caps_data_adj (1).joblib'
FileNotFoundError: [Errno 2] No such file or directory: '../data_flickr30k/data/flickr30k_val_lowered_images_data_adj.joblib'
FileNotFoundError: [Errno 2] No such file or directory: '../data_flickr30k/data/flickr30k_val_lowered_caps_data_adj (1).joblib'

The same problem occurs on the MS COCO dataset. 

Can you provide these source files? Thanks！

**Comment by okeike** [comment]
Thanks for asking, you need to download the additional basic files (please refer to **Data** of **README**), and revise the paths.
